name: "Wisharr"
description: "L'outil de gestion de listes de souhaits et de suivi de prix pour votre foyer."
version: "0.1.0"
slug: "wisharr"
arch:
- aarch64
- amd64
- armv7
init: false
startup: services
panel_icon: "mdi:cart-heart"
panel_title: "Wisharr"
host_network: true
homeassistant_api: true
auth_api: true
options:
  log_level: "info"
  port: 3000
schema:
  log_level: "fatal|error|warn|info|debug|trace"
  port: "port"
